<?php
	/*
	 * list2tree.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>
			.tree,.tree ul,.tree ol{list-style-type:none;}
			.tree li span{cursor:pointer;}
			.tree li .tree_open_tick::before{content:"\25B6";margin-right:6px;}
			.tree li .tree_opened::before{content:"\25BC";}
		</style>
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				list2tree(document.getElementById('tree_list'), 'span', function(object, action){
					if(action)
						object.classList.add('tree_opened');
					else
						object.classList.remove('tree_opened');
				});
			}, false)
		</script>
	</head>
	<body>
		<ul id="tree_list" class="tree">
			<li>node a</li>
			<li>
				<span class="tree_open_tick">node b</span>
				<ul>
					<li>node ba</li>
					<li>
						<span class="tree_open_tick">node bb</span>
						<ul>
							<li>node bba</li>
							<li>node bbb</li>
						</ul>
					</li>
					<li>
						<span class="tree_open_tick">node bc</span>
						<ul>
							<li>node bca</li>
							<li>node bcb</li>
							<li>node bcc</li>
							<li>node bcd</li>
						</ul>
					</li>
				</ul>
			</li>
			<li>node c</li>
		</ul>
	</body>
</html>