<?php
	/*
	 * loremIpsumGenerator.js library test
	 *
	 * Note:
	 *  looks for a library at ../lib
	 *  looks for a library at ..
	 */

	if(
		(!is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml'))) &&
		(!is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
	){
		echo __DIR__.'/../lib/'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		echo __DIR__.'/../'.basename(__FILE__, '.phtml').' is not a file'.PHP_EOL;
		exit();
	}
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<script>
			document.addEventListener('DOMContentLoaded', function(){
				<?php
					if(is_file(__DIR__.'/../lib/'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../lib/'.basename(__FILE__, '.phtml');
					else if(is_file(__DIR__.'/../'.basename(__FILE__, '.phtml')))
						require __DIR__.'/../'.basename(__FILE__, '.phtml');
				?>

				document.getElementById('start-wp').addEventListener('click', function(){
					var startTag='';
					var endTag='';
					if(document.getElementById('params-start-end-tags').checked)
					{
						startTag=document.getElementById('params-start-tag').value;
						endTag=document.getElementById('params-end-tag').value;
					}

					var textarea=document.getElementById('output');
					textarea.value=generateLoremIpsumWP(
						document.getElementById('params-words').value,
						document.getElementById('params-paragraphs').value,
						document.getElementById('params-start-lipsum').checked,
						document.getElementById('params-double-newline').checked,
						startTag, endTag
					);
				}, false);
				document.getElementById('start-b').addEventListener('click', function(){
					var startTag='';
					var endTag='';
					if(document.getElementById('params-start-end-tags').checked)
					{
						startTag=document.getElementById('params-start-tag').value;
						endTag=document.getElementById('params-end-tag').value;
					}

					var textarea=document.getElementById('output');
					textarea.value=generateLoremIpsumB(
						document.getElementById('params-bytes').value,
						startTag, endTag
					);
				}, false);

				// automatic test
					var testOutput=document.getElementById('test-output');
					var content;
					var i;
					var failed=false;
					testOutput.innerHTML='';

					testOutput.innerHTML+='-> Testing generateLoremIpsumWP\n';
						testOutput.innerHTML+=' -> single newline';
							content=generateLoremIpsumWP(30, 4, false, false, '<p>', '</p>').split("\n");
							if(content.length === 4)
								testOutput.innerHTML+=' [ OK ]\n';
							else
							{
								testOutput.innerHTML+=' [FAIL]\n';
								failed=true;
							}
							for(i=0; i<content.length; i++)
							{
								testOutput.innerHTML+='  -> paragraph '+i;

								if(
									(content[i].substring(0, 3) === '<p>') &&
									(content[i].substring(content[i].length-4) === '</p>')
								)
									testOutput.innerHTML+=' [ OK ]';
								else
								{
									testOutput.innerHTML+=' [FAIL]';
									failed=true;
								}

								if(content[i].trim().split(/\s+/).length === 30)
									testOutput.innerHTML+=' [ OK ]\n';
								else
								{
									testOutput.innerHTML+=' [FAIL]\n';
									failed=true;
								}
							}
						testOutput.innerHTML+=' -> double newline/start with lipsum';
							content=generateLoremIpsumWP(30, 4, true, true, '<p>', '</p>').split("\n");
							if(content.length === 7)
								testOutput.innerHTML+=' [ OK ]\n';
							else
							{
								testOutput.innerHTML+=' [FAIL]\n';
								failed=true;
							}
							for(i=0; i<content.length; i++)
							{
								testOutput.innerHTML+='  -> paragraph '+i;

								if(i === 0)
								{
									testOutput.innerHTML+=' (Lorem ipsum...)';

									if(content[i].substring(0, 54) === '<p>Lorem ipsum dolor sit amet consectetuer adipiscing ')
										testOutput.innerHTML+=' [ OK ]';
									else
									{
										testOutput.innerHTML+=' [FAIL]';
										failed=true;
									}
								}

								if(i%2 === 0)
								{
									if(
										(content[i].substring(0, 3) === '<p>') &&
										(content[i].substring(content[i].length-4) === '</p>')
									)
										testOutput.innerHTML+=' [ OK ]';
									else
									{
										testOutput.innerHTML+=' [FAIL]';
										failed=true;
									}

									if(content[i].trim().split(/\s+/).length === 30)
										testOutput.innerHTML+=' [ OK ]\n';
									else
									{
										testOutput.innerHTML+=' [FAIL]\n';
										failed=true;
									}
								}
								else
								{
									testOutput.innerHTML+=' (empty line)';

									if(content[i] === '')
										testOutput.innerHTML+=' [ OK ]\n';
									else
									{
										testOutput.innerHTML+=' [FAIL]\n';
										failed=true;
									}
								}
							}

					testOutput.innerHTML+='-> Testing generateLoremIpsumB';
						content=generateLoremIpsumB(400, '<p>', '</p>');
						if(
							(content.substring(0, 3) === '<p>') &&
							(content.substring(content.length-4) === '</p>')
						)
							testOutput.innerHTML+=' [ OK ]';
						else
						{
							testOutput.innerHTML+=' [FAIL]';
							failed=true;
						}
						if(content.length === 407)
							testOutput.innerHTML+=' [ OK ]\n';
						else
						{
							testOutput.innerHTML+=' [FAIL]\n';
							failed=true;
						}

					if(failed)
						testOutput.innerHTML+='\nTest failed';
					else
						testOutput.innerHTML+='\nTest passed';
			}, false);
		</script>
	</head>
	<body>
		<div><pre id="test-output">Test was not executed</pre></div>
		<hr>
		<div id="params">
			<input type="text" id="params-paragraphs" value="4"> paragraphs,
			<input type="text" id="params-words" value="30"> words,
			<input type="checkbox" id="params-start-lipsum" checked>start with Lorem ipsum
			<button id="start-wp">Generate</button>
			<br>
			<input type="text" id="params-bytes" value="400"> characters
			<button id="start-b">Generate</button>
			<br>
			<input type="checkbox" id="params-start-end-tags">
			start tag: <input type="text" id="params-start-tag" value="<p>">,
			end tag: <input type="text" id="params-end-tag" value="</p>">,
			<input type="checkbox" id="params-double-newline" checked>double \n
		</div>
		<textarea id="output"></textarea>
	</body>
</html>